swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{compteId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Récupérer toutes les transactions du mois en cours sur le compte choisis
      description: Retourne la liste de toutes les transactions groupées par compte pour le mois en cours.
      parameters:
        - name: CompteId
          in: path
          description: ID du compte pour la transaction à récupérer
          required: true
          type: string
      responses:
        200:
          description: Succès. Retourne la liste des transactions pour le mois en cours sur le compte spécifiée.
        404:
          description: Aucune transaction trouvée pour le mois en cours.
        500:
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Récupérer les détails d'une transaction spécifique
      description: Retourne les détails d'une transaction spécifiée par ID.
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à récupérer
          required: true
          type: string
      responses:
        200:
          description: Succès. Retourne les détails de la transaction spécifiée.
        404:
          description: Transaction non trouvée.
        500:
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Modifier les informations d'une transaction
      description: Modifie les informations d'une transaction spécifiée par ID.
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction à modifier
          required: true
          type: string
        - name: body
          in: body
          description: Nouvelles informations de la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionInput'
      responses:
        200:
          description: Succès. Retourne les détails de la transaction modifiée (Note/Categorie).
        404:
          description: Transaction non trouvée.
        500:
          description: Internal Server Error

definitions:
  TransactionInput:
    type: object
    properties:
      Category:
        type: string
        description: Montant de la transaction
      Note:
        type: string
        description: Description de la transaction
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string